# Generated by Django 4.2.4 on 2023-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neumatico',
            name='ancho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='relacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neumatico',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
